[mcp_servers.mysql-data]
command = "cmd"
args = [
    "/c",
    "npx",
    "-y",
    "@benborla29/mcp-server-mysql",
]

[mcp_servers.mysql-data.env]
MYSQL_HOST = "192.168.50.50"
MYSQL_PORT = "3307"
MYSQL_USER = "root"
MYSQL_PASS = "maplestory"
MYSQL_DB = "maple-data"

[mcp_servers.mysql-game]
command = "cmd"
args = [
    "/c",
    "npx",
    "-y",
    "@benborla29/mcp-server-mysql",
]

[mcp_servers.mysql-game.env]
MYSQL_HOST = "192.168.50.50"
MYSQL_PORT = "3307"
MYSQL_USER = "root"
MYSQL_PASS = "maplestory"
MYSQL_DB = "game-server"
ALLOW_INSERT_OPERATION = "true"
ALLOW_UPDATE_OPERATION = "true"
ALLOW_DELETE_OPERATION = "true"
